import type {
  DimensionInput,
  VerificationContext,
  VerificationFactor,
} from '../../scoring/src/index.js';
import type { SeedManifest, SeedProvider } from './types.js';

const observedAt = '2026-09-25T20:00:00.000Z';

function dimensions(
  maturity: number,
  evidence: number,
  freshness: number,
  security: number | null,
  domain: number,
  options: { publisherHeavy?: boolean; highPrivilege?: boolean; securityMissing?: string } = {},
): DimensionInput[] {
  const present = (
    key: DimensionInput['key'],
    raw: number,
    confidence: number,
    reason: string,
  ): DimensionInput => ({
    key,
    raw,
    confidence,
    coverage: confidence,
    applicability: 'applicable',
    state: 'present',
    reasons: [reason],
    missing: [],
    evidenceIds: [],
  });
  return [
    present(
      'maturity',
      maturity,
      0.82,
      'Current primary sources and an active release or support history were reviewed.',
    ),
    present(
      'evidence_strength',
      evidence,
      options.publisherHeavy ? 0.48 : 0.72,
      options.publisherHeavy
        ? 'Material capability evidence is publisher-produced and scoped accordingly.'
        : 'Multiple primary records support the scoped capability description.',
    ),
    present('freshness_support', freshness, 0.88, 'Primary sources were refreshed on 2026-09-25.'),
    security === null
      ? {
          key: 'security_provenance',
          raw: null,
          confidence: 0,
          coverage: 0,
          applicability: 'applicable',
          state: 'missing',
          highPrivilege: options.highPrivilege,
          reasons: [],
          missing: [
            options.securityMissing ??
              'No reviewed security or permission evidence for this scope.',
          ],
          evidenceIds: [],
        }
      : {
          ...present(
            'security_provenance',
            security,
            options.highPrivilege ? 0.64 : 0.72,
            'Identity, license, and documented permission boundaries were reviewed; this is not a safety certification.',
          ),
          highPrivilege: options.highPrivilege,
        },
    present(
      'domain_confidence',
      domain,
      0.88,
      'The documented capability directly serves the assigned domain.',
    ),
  ];
}

function factors(
  overrides: Partial<Record<VerificationFactor['key'], number>> = {},
): VerificationFactor[] {
  const labels: Record<VerificationFactor['key'], string> = {
    evidence_gap: 'Decision-relevant evidence gap',
    privilege_blast_radius: 'Privilege and blast radius',
    project_criticality: 'Project criticality',
    novelty_provenance: 'Novelty or provenance uncertainty',
    claim_magnitude_conflict: 'Claim magnitude or conflict',
    benchmarkability: 'Benchmarkability',
    decision_urgency: 'Decision urgency',
    irreversibility_switching_cost: 'Irreversibility or switching cost',
  };
  return Object.keys(labels).map((key) => ({
    key: key as VerificationFactor['key'],
    value: overrides[key as VerificationFactor['key']] ?? 1,
    reasons: [labels[key as VerificationFactor['key']]],
    evidenceIds: [],
  }));
}

type Source = SeedProvider['sources'][number];
type Claim = SeedProvider['claims'][number];

function source(
  key: string,
  url: string,
  title: string,
  owner: string,
  type: string,
  authorityScope: string,
  observation: string,
): Source {
  return { key, url, title, owner, type, authorityScope, observation, observedAt };
}

function claim(
  key: string,
  sourceKey: string,
  claimant: string,
  predicate: string,
  value: unknown,
  scope: string,
  limitations: string[],
  options: {
    claimantRelation?: Claim['claimantRelation'];
    independence?: Claim['evidence']['independence'];
    direction?: Claim['evidence']['direction'];
    strength?: Claim['evidence']['strength'];
    applicability?: Claim['evidence']['applicability'];
  } = {},
): Claim {
  return {
    key,
    sourceKey,
    claimant,
    claimantRelation: options.claimantRelation ?? 'publisher',
    predicate,
    value,
    scope,
    evidence: {
      type: 'documentation_inspection',
      producer: 'Maestro seed curation',
      methodVersion: 'primary-source-review-v1',
      independence: options.independence ?? 'publisher_only',
      direction: options.direction ?? 'supports',
      strength: options.strength ?? 'moderate',
      applicability: options.applicability ?? 'exact',
      limitations,
    },
  };
}

function verificationContext(value: VerificationContext = {}): VerificationContext {
  return value;
}

export const catalogSeedV1: SeedManifest = {
  schemaVersion: 'maestro-seed-v1',
  seedRevision: 'discovery-v0-seed-2026-09-25.1',
  observedAt,
  taxonomy: {
    key: 'maestro-domains',
    version: 1,
    domains: [
      {
        key: 'ai-engineering',
        label: 'AI engineering',
        definition: 'Capabilities used to build, evaluate, and operate AI-assisted systems.',
      },
      {
        key: 'ai-coding-systems',
        label: 'AI coding systems',
        definition: 'Capabilities that assist or coordinate software-development work.',
        parentKey: 'ai-engineering',
      },
      {
        key: 'agent-control-planes',
        label: 'Agent control planes',
        definition: 'Surfaces and runtimes that coordinate software agents.',
        parentKey: 'ai-coding-systems',
      },
      {
        key: 'skills-plugins',
        label: 'Skills and plugins',
        definition: 'Packaging and configuration surfaces for reusable agent capabilities.',
        parentKey: 'ai-coding-systems',
      },
      {
        key: 'context-code-intelligence',
        label: 'Context and code intelligence',
        definition: 'Capabilities that retrieve, structure, or reduce coding context.',
        parentKey: 'ai-coding-systems',
      },
      {
        key: 'agent-workflow-evaluation',
        label: 'Agent workflow evaluation',
        definition: 'Evidence and evaluation of coding-agent workflows.',
        parentKey: 'ai-coding-systems',
      },
      {
        key: 'capability-infrastructure',
        label: 'Capability infrastructure',
        definition: 'Protocols, registries, and evaluation infrastructure for capabilities.',
        parentKey: 'ai-engineering',
      },
      {
        key: 'tool-agent-protocols',
        label: 'Tool and agent protocols',
        definition: 'Transport contracts between agents, applications, and tools.',
        parentKey: 'capability-infrastructure',
      },
      {
        key: 'registries-discovery',
        label: 'Registries and discovery',
        definition: 'Identity and metadata sources used to discover capabilities.',
        parentKey: 'capability-infrastructure',
      },
      {
        key: 'observability-evaluation',
        label: 'Observability and evaluation',
        definition: 'Measured observations and evaluation tooling for AI-assisted work.',
        parentKey: 'capability-infrastructure',
      },
      {
        key: 'software-engineering-foundations',
        label: 'Software engineering foundations',
        definition: 'Established technologies used to build and operate software.',
      },
      {
        key: 'languages-runtimes',
        label: 'Languages and runtimes',
        definition: 'Programming languages and their supported execution runtimes.',
        parentKey: 'software-engineering-foundations',
      },
      {
        key: 'infrastructure-as-code',
        label: 'Infrastructure as code',
        definition: 'Declarative infrastructure planning and state-management capabilities.',
        parentKey: 'software-engineering-foundations',
      },
    ],
  },
  providers: [
    {
      key: 'openhands',
      name: 'OpenHands',
      kind: 'framework',
      description:
        'A software-agent SDK and Agent Canvas control surface with replaceable workspace backends.',
      aliases: ['OpenHands Software Agent SDK', 'Agent Canvas'],
      identity: { scheme: 'github_repository', value: 'OpenHands/software-agent-sdk' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['agent-control-planes'],
      capability: {
        key: 'agent-execution-control',
        name: 'Coordinate software-agent execution',
        description: 'Run and observe software-agent conversations against configured workspaces.',
        deliveryMode: 'sdk-and-control-surface',
        assertionState: 'observed',
        effects: ['read_data', 'write_data', 'execute_process', 'network'],
      },
      licenseBusiness:
        'Reviewed SDK repository identifies MIT; hosted services have separate terms.',
      sources: [
        source(
          'repo',
          'https://github.com/OpenHands/software-agent-sdk',
          'OpenHands Software Agent SDK',
          'OpenHands',
          'canonical_repository',
          'Repository code, license, and SDK boundary',
          'Repository is active and identifies an MIT license.',
        ),
        source(
          'canvas',
          'https://github.com/OpenHands/docs/blob/main/openhands/usage/agent-canvas/overview.mdx',
          'Agent Canvas overview',
          'OpenHands',
          'official_docs',
          'Published product and backend behavior',
          'Agent Canvas connects a browser control surface to local, Docker, VM, Modal, or cloud backends.',
        ),
      ],
      claims: [
        claim(
          'sdk-boundary',
          'repo',
          'OpenHands',
          'provides_capability',
          'software-agent SDK and server contracts',
          'Current canonical SDK repository observed 2026-09-25.',
          ['Repository interfaces can change by version.'],
        ),
        claim(
          'canvas-backends',
          'canvas',
          'OpenHands',
          'supports_execution_backends',
          ['local', 'Docker', 'VM', 'Modal', 'cloud'],
          'Agent Canvas overview at observation time.',
          ['Backend availability does not establish hostile-code isolation.'],
        ),
      ],
      scoreDimensions: dimensions(84, 76, 92, 64, 92, { highPrivilege: true }),
      verificationFactors: factors({
        privilege_blast_radius: 4,
        project_criticality: 2,
        evidence_gap: 2,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['documentation_contract', 'sandbox_install_smoke', 'privacy_permission'],
      nextVerification:
        'For a real project, pin the backend and measure workspace, network, credential, and cancellation behavior.',
      compatibility: {
        noRemoteSourceTransfer: 'unknown',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'fail',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'github-agentic-workflows',
      name: 'GitHub Agentic Workflows',
      kind: 'workflow',
      description:
        'Repository-native AI workflows authored in Markdown and compiled to GitHub Actions.',
      aliases: ['gh-aw'],
      identity: { scheme: 'vendor_product', value: 'github:agentic-workflows' },
      version: { label: 'public-preview-observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['agent-control-planes'],
      capability: {
        key: 'repository-agentic-workflows',
        name: 'Run guarded repository automations',
        description:
          'Compile natural-language workflow definitions into guarded GitHub Actions workflows.',
        deliveryMode: 'hosted-product-and-cli',
        assertionState: 'observed',
        effects: ['read_data', 'write_data', 'network', 'external_mutation', 'spend'],
      },
      licenseBusiness:
        'GitHub service terms apply; the canonical gh-aw compiler repository identifies MIT.',
      sources: [
        source(
          'docs',
          'https://docs.github.com/en/copilot/concepts/agents/about-github-agentic-workflows',
          'About GitHub Agentic Workflows',
          'GitHub',
          'official_docs',
          'Current product status, workflow, and security model',
          'Official docs identify the feature as public preview with read-only defaults and declared safe outputs.',
        ),
        source(
          'repo',
          'https://github.com/github/gh-aw',
          'GitHub Agentic Workflows compiler',
          'GitHub',
          'canonical_repository',
          'Compiler source and license',
          'Canonical repository is active and identifies an MIT license.',
        ),
      ],
      claims: [
        claim(
          'compile',
          'docs',
          'GitHub',
          'compiles_definition_to',
          'pinned GitHub Actions workflow',
          'Public-preview agentic workflow documented 2026-09-25.',
          ['Hosted availability and behavior may change during preview.'],
        ),
        claim(
          'guardrails',
          'docs',
          'GitHub',
          'documents_guardrails',
          [
            'read-only default',
            'safe outputs',
            'secrets outside agent runtime',
            'firewalled execution',
          ],
          'Official security description for GitHub Agentic Workflows.',
          ['Publisher documentation is not independent adversarial verification.'],
        ),
      ],
      scoreDimensions: dimensions(82, 78, 94, 72, 88, { highPrivilege: true }),
      verificationFactors: factors({
        privilege_blast_radius: 4,
        irreversibility_switching_cost: 2,
        project_criticality: 3,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['documentation_contract', 'privacy_permission', 'functional_black_box'],
      nextVerification:
        'Review the compiled workflow, token scopes, safe outputs, network policy, and exact billing before project use.',
      compatibility: {
        noRemoteSourceTransfer: 'fail',
        macos: 'unknown',
        noAutomaticWorkspaceWrites: 'unknown',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'capa',
      name: 'CAPA',
      kind: 'framework',
      description:
        'A capability configuration source that fans out native agent settings and services.',
      aliases: ['Capability Manager'],
      identity: { scheme: 'github_repository', value: 'infragate/capa' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['skills-plugins'],
      capability: {
        key: 'capability-configuration-fanout',
        name: 'Generate agent capability configuration',
        description:
          'Project declared capabilities into host-native rules, skills, plugins, and MCP configuration.',
        deliveryMode: 'local-cli-and-services',
        assertionState: 'observed',
        effects: ['read_data', 'write_data', 'credential_use', 'network'],
      },
      licenseBusiness: 'Canonical repository identifies MIT.',
      sources: [
        source(
          'repo',
          'https://github.com/infragate/capa',
          'CAPA repository',
          'Infragate',
          'canonical_repository',
          'Code, activity, and license',
          'Repository is active and identifies an MIT license.',
        ),
        source(
          'docs',
          'https://capa.infragate.ai/getting-started/how-capa-works/',
          'How CAPA works',
          'Infragate',
          'official_docs',
          'Configuration generation architecture',
          'Official docs describe capabilities.yaml as a source used to generate agent-native configuration.',
        ),
      ],
      claims: [
        claim(
          'source-of-truth',
          'docs',
          'CAPA publisher',
          'uses_configuration_source',
          'capabilities.yaml',
          'Documented CAPA configuration workflow.',
          ['A configuration source does not prove suitability of configured capabilities.'],
        ),
        claim(
          'fanout',
          'docs',
          'CAPA publisher',
          'generates',
          ['rules', 'skills', 'MCP configuration', 'agent configuration'],
          'Documented supported configuration surfaces.',
          ['Native host formats and support can drift.'],
        ),
      ],
      scoreDimensions: dimensions(70, 67, 88, 55, 83, { highPrivilege: true }),
      verificationFactors: factors({
        privilege_blast_radius: 3,
        evidence_gap: 2,
        novelty_provenance: 2,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['documentation_contract', 'source_review', 'sandbox_install_smoke'],
      nextVerification:
        'Preview generated changes against a disposable workspace and verify credential and ownership boundaries.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'unknown',
        noAutomaticWorkspaceWrites: 'fail',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'aas-core',
      name: 'AAS Core',
      kind: 'registry',
      description: 'Local discovery and stack planning over a large catalog of agent skills.',
      aliases: ['Agentic Awesome Skills', 'AAS'],
      identity: { scheme: 'github_repository', value: 'sickn33/agentic-awesome-skills' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['skills-plugins', 'registries-discovery'],
      capability: {
        key: 'skill-discovery-planning',
        name: 'Discover and plan skill stacks',
        description: 'Search skills locally and produce reviewable stack plans.',
        deliveryMode: 'local-cli-and-mcp',
        assertionState: 'observed',
        effects: ['read_data', 'write_data'],
      },
      licenseBusiness:
        'Project tooling identifies MIT; every upstream skill retains its own license.',
      sources: [
        source(
          'repo',
          'https://github.com/sickn33/agentic-awesome-skills',
          'Agentic Awesome Skills',
          'AAS maintainers',
          'canonical_repository',
          'Tooling code, catalog, and license',
          'Repository is active and identifies an MIT project license.',
        ),
        source(
          'docs',
          'https://github.com/sickn33/agentic-awesome-skills/blob/main/docs/users/aas-core.md',
          'AAS Core user guide',
          'AAS maintainers',
          'official_docs',
          'Local discovery and plan behavior',
          'AAS Core documentation describes discovery, selection, validation, and stack plans.',
        ),
      ],
      claims: [
        claim(
          'local-discovery',
          'docs',
          'AAS maintainers',
          'supports',
          'local skill discovery and selection',
          'AAS Core user workflow.',
          ['Catalog size is not evidence of individual skill quality.'],
        ),
        claim(
          'plans',
          'docs',
          'AAS maintainers',
          'produces',
          'reviewable stack plan',
          'AAS Core planning workflow.',
          ['A valid plan does not certify upstream behavior or permissions.'],
        ),
      ],
      scoreDimensions: dimensions(66, 61, 90, 48, 82, { highPrivilege: true }),
      verificationFactors: factors({
        evidence_gap: 3,
        privilege_blast_radius: 3,
        novelty_provenance: 3,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['identity_metadata', 'provenance_license', 'static_scan'],
      nextVerification:
        'Resolve and inspect each selected upstream skill; do not treat catalog inclusion as approval.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'unknown',
        noAutomaticWorkspaceWrites: 'unknown',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'openai-plugins',
      name: 'OpenAI plugins',
      kind: 'plugin',
      description:
        'An official plugin container for skills with optional MCP servers, hooks, and UI.',
      aliases: ['ChatGPT plugins', 'Codex plugins'],
      identity: { scheme: 'vendor_product', value: 'openai:plugins' },
      version: { label: 'docs-observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['skills-plugins'],
      capability: {
        key: 'plugin-package-distribution',
        name: 'Package reusable agent capabilities',
        description:
          'Distribute skills and optional live integrations through an official plugin contract.',
        deliveryMode: 'platform-container',
        assertionState: 'observed',
        effects: ['read_data', 'write_data', 'network', 'external_mutation'],
      },
      licenseBusiness:
        'Platform feature; each plugin and included component has its own license and terms.',
      sources: [
        source(
          'concepts',
          'https://developers.openai.com/plugins/concepts/plugins',
          'Plugin architecture',
          'OpenAI',
          'official_docs',
          'Plugin component contract',
          'Official docs describe a plugin package containing skills and optional integration surfaces.',
        ),
        source(
          'build',
          'https://developers.openai.com/plugins/build/plugins',
          'Package your plugin',
          'OpenAI',
          'official_docs',
          'Current packaging contract',
          'Official build guidance documents the plugin manifest and package structure.',
        ),
        source(
          'security',
          'https://developers.openai.com/plugins/guides/security-privacy',
          'Plugin Security and Privacy',
          'OpenAI',
          'official_docs',
          'Publisher security expectations',
          'Security guidance requires scoped authorization, validation, consent, and care around irreversible actions.',
        ),
      ],
      claims: [
        claim(
          'container',
          'concepts',
          'OpenAI',
          'packages',
          ['skills', 'optional MCP servers', 'optional hooks or UI'],
          'Official plugin architecture at observation time.',
          ['Host support and packaging fields are versioned platform contracts.'],
        ),
        claim(
          'security-guidance',
          'security',
          'OpenAI',
          'documents_controls',
          ['least privilege', 'explicit consent', 'server-side validation'],
          'Official plugin security guidance.',
          ['Publisher guidance does not verify every third-party plugin.'],
        ),
      ],
      scoreDimensions: dimensions(82, 75, 94, 68, 90, { highPrivilege: true }),
      verificationFactors: factors({
        privilege_blast_radius: 4,
        evidence_gap: 2,
        irreversibility_switching_cost: 2,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: [
        'documentation_contract',
        'provenance_license',
        'privacy_permission',
        'static_scan',
      ],
      nextVerification:
        'Assess the exact plugin artifact, hooks, MCP endpoints, scopes, and host version before installation.',
      compatibility: {
        noRemoteSourceTransfer: 'unknown',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'unknown',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'mcp-registry',
      name: 'Official MCP Registry',
      kind: 'registry',
      description: 'The official metadata index and API for discoverable MCP servers.',
      aliases: ['MCP Registry'],
      identity: { scheme: 'github_repository', value: 'modelcontextprotocol/registry' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['registries-discovery', 'tool-agent-protocols'],
      capability: {
        key: 'mcp-server-discovery',
        name: 'Discover MCP server metadata',
        description: 'Publish and query identity and lifecycle metadata for MCP servers.',
        deliveryMode: 'registry-api',
        assertionState: 'observed',
        effects: ['read_data', 'network'],
      },
      licenseBusiness:
        'Repository is in an MIT-to-Apache-2.0 transition; server entries keep their own licenses.',
      sources: [
        source(
          'repo',
          'https://github.com/modelcontextprotocol/registry',
          'Official MCP Registry',
          'Model Context Protocol project',
          'canonical_repository',
          'Registry code, status, and licensing notice',
          'Canonical repository is active and its license file documents an MIT-to-Apache-2.0 transition.',
        ),
        source(
          'api',
          'https://github.com/modelcontextprotocol/registry/blob/main/docs/reference/api/official-registry-api.md',
          'Official Registry API reference',
          'Model Context Protocol project',
          'official_docs',
          'Registry record and API contract',
          'API reference defines server metadata records and lifecycle fields.',
        ),
      ],
      claims: [
        claim(
          'metadata-index',
          'api',
          'MCP project',
          'provides',
          'discoverable MCP server metadata API',
          'Official registry API contract.',
          ['Registry records do not establish behavioral safety or project fit.'],
        ),
        claim(
          'license-transition',
          'repo',
          'MCP project',
          'license_state',
          'MIT to Apache-2.0 transition',
          'Repository license notice observed 2026-09-25.',
          ['Contribution-level license applicability may differ during transition.'],
        ),
      ],
      scoreDimensions: dimensions(76, 72, 90, 60, 88),
      verificationFactors: factors({
        evidence_gap: 2,
        novelty_provenance: 2,
        privilege_blast_radius: 1,
      }),
      verificationContext: verificationContext({ noActiveDecisionInReviewHorizon: true }),
      verificationState: 'candidate',
      verificationModes: ['identity_metadata', 'provenance_license'],
      nextVerification:
        'Verify an individual server namespace, artifact, version, permissions, and behavior separately.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'pass',
        contextReduction: 'no',
        setupReversibility: 'strong',
      },
    },
    {
      key: 'context-mode',
      name: 'Context Mode',
      kind: 'mcp_server',
      description:
        'A local MCP and hook integration that indexes or summarizes large tool outputs before model context.',
      aliases: ['context-mode'],
      identity: { scheme: 'github_repository', value: 'mksglu/context-mode' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['context-code-intelligence'],
      capability: {
        key: 'context-output-optimization',
        name: 'Reduce large tool-output context',
        description:
          'Externalize, index, search, or summarize tool output before it enters model context.',
        deliveryMode: 'local-mcp-and-hooks',
        assertionState: 'publisher_declared',
        effects: ['read_data', 'write_data', 'execute_process'],
      },
      licenseBusiness:
        'Canonical repository license is Elastic License 2.0, source-available rather than OSI open source.',
      sources: [
        source(
          'repo',
          'https://github.com/mksglu/context-mode',
          'Context Mode repository',
          'Context Mode publisher',
          'canonical_repository',
          'Code, setup, activity, and license',
          'Repository is active; license file identifies Elastic License 2.0.',
        ),
        source(
          'benchmark',
          'https://github.com/mksglu/context-mode/blob/main/BENCHMARK.md',
          'Context Mode benchmark',
          'Context Mode publisher',
          'benchmark',
          'Publisher benchmark fixtures and measurements',
          'Publisher benchmark reports 96% overall context savings across 21 selected scenarios and discloses fixtures.',
        ),
      ],
      claims: [
        claim(
          'local-index',
          'repo',
          'Context Mode publisher',
          'uses',
          'local SQLite FTS5 indexing and output handling',
          'Repository documentation observed 2026-09-25.',
          ['Local execution inherits host filesystem authority unless separately confined.'],
        ),
        claim(
          'savings',
          'benchmark',
          'Context Mode publisher',
          'reports_context_savings_percent',
          96,
          'Publisher-run 21-scenario benchmark: 376 KB raw data and 16.5 KB context.',
          [
            'Publisher-produced benchmark; not independently reproduced for this project.',
            'Task quality equivalence is not established by byte reduction alone.',
          ],
        ),
      ],
      scoreDimensions: dimensions(62, 58, 96, null, 92, {
        publisherHeavy: true,
        highPrivilege: true,
        securityMissing:
          'No reviewed permission-boundary evidence establishes filesystem and subprocess effects for the evaluated version.',
      }),
      verificationFactors: factors({
        evidence_gap: 4,
        claim_magnitude_conflict: 4,
        benchmarkability: 4,
        decision_urgency: 3,
        privilege_blast_radius: 3,
      }),
      verificationContext: verificationContext({
        largeQuantitativeClaimWithBoundedTest: true,
        blockingUnknownNearDecision: true,
      }),
      verificationState: 'candidate',
      verificationModes: [
        'provenance_license',
        'source_review',
        'reproducible_benchmark',
        'project_trial',
      ],
      nextVerification:
        'Pin a version and replay representative coding tasks on macOS; compare tokens, quality, latency, failures, filesystem effects, and reversibility.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'unknown',
        noAutomaticWorkspaceWrites: 'unknown',
        contextReduction: 'yes',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'better-harness',
      name: 'Better Harness',
      kind: 'product',
      description:
        'An evidence-bounded evaluator of coding-agent work loops and configured project mechanisms.',
      aliases: ['better-harness'],
      identity: { scheme: 'github_repository', value: 'QoderAI/better-harness' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['agent-workflow-evaluation'],
      capability: {
        key: 'agent-workflow-evaluation',
        name: 'Evaluate coding-agent workflow evidence',
        description: 'Inspect project and session evidence and produce scoped workflow findings.',
        deliveryMode: 'host-plugins-and-cli',
        assertionState: 'observed',
        effects: ['read_data', 'write_data'],
      },
      licenseBusiness: 'Canonical repository identifies MIT.',
      sources: [
        source(
          'repo',
          'https://github.com/QoderAI/better-harness',
          'Better Harness repository',
          'QoderAI',
          'canonical_repository',
          'Product boundary, adapters, and license',
          'Repository is active, identifies MIT, and documents host-specific evidence boundaries.',
        ),
        source(
          'design',
          'https://github.com/QoderAI/better-harness/blob/main/DESIGN.md',
          'Better Harness design',
          'QoderAI',
          'official_docs',
          'Evidence and finding semantics',
          'Design material distinguishes configured mechanisms from observed use and keeps missing evidence explicit.',
        ),
      ],
      claims: [
        claim(
          'evidence-loop',
          'repo',
          'Better Harness publisher',
          'analyzes',
          'coding-agent work-loop evidence',
          'Current repository product boundary.',
          ['Supported evidence differs by host adapter.'],
        ),
        claim(
          'missing-explicit',
          'design',
          'Better Harness publisher',
          'represents',
          'missing evidence explicitly',
          'Published design and report behavior.',
          ['Report findings remain tool-attributed observations.'],
        ),
      ],
      scoreDimensions: dimensions(68, 68, 92, 56, 86, { highPrivilege: true }),
      verificationFactors: factors({
        evidence_gap: 2,
        privilege_blast_radius: 2,
        benchmarkability: 3,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['source_review', 'functional_black_box', 'project_trial'],
      nextVerification:
        'Run on a representative, non-sensitive session set and inspect host coverage, redaction, and finding reproducibility.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'unknown',
        contextReduction: 'no',
        setupReversibility: 'strong',
      },
    },
    {
      key: 'codeburn',
      name: 'CodeBurn',
      kind: 'product',
      description:
        'A local-first coding-agent usage and cost attribution tool over supported session formats.',
      aliases: ['codeburn'],
      identity: { scheme: 'github_repository', value: 'getagentseal/codeburn' },
      version: { label: '0.9.25' },
      lifecycle: 'active',
      domains: ['observability-evaluation'],
      capability: {
        key: 'coding-agent-usage-observability',
        name: 'Attribute coding-agent token usage',
        description:
          'Parse supported local session records into model, project, task, token, and estimated-cost observations.',
        deliveryMode: 'local-cli-and-desktop',
        assertionState: 'observed',
        effects: ['read_data'],
      },
      licenseBusiness:
        'Canonical repository identifies MIT; desktop and optional services may have separate telemetry behavior.',
      sources: [
        source(
          'repo',
          'https://github.com/getagentseal/codeburn',
          'CodeBurn repository',
          'AgentSeal',
          'canonical_repository',
          'Product boundary, provider parsers, and license',
          'Repository is active, identifies MIT, and documents local coding-agent usage attribution.',
        ),
        source(
          'providers',
          'https://codeburn.app/docs/providers',
          'CodeBurn provider coverage',
          'AgentSeal',
          'official_docs',
          'Measured and estimated provider coverage',
          'Provider documentation distinguishes coverage and available usage fields by coding tool.',
        ),
      ],
      claims: [
        claim(
          'usage',
          'repo',
          'CodeBurn publisher',
          'attributes',
          ['tokens', 'estimated cost', 'model', 'project', 'task'],
          'Supported local coding-agent session formats.',
          [
            'Monetary values can be accounting equivalents rather than incremental subscription charges.',
          ],
        ),
        claim(
          'coverage',
          'providers',
          'CodeBurn publisher',
          'coverage_varies_by',
          'provider and host session format',
          'Published provider coverage documentation.',
          ['Host file formats are external and can drift.'],
        ),
      ],
      scoreDimensions: dimensions(72, 70, 94, 62, 85),
      verificationFactors: factors({
        evidence_gap: 2,
        benchmarkability: 3,
        privilege_blast_radius: 2,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['source_review', 'functional_black_box', 'privacy_permission'],
      nextVerification:
        'Compare parsed raw fields with source session records and review redaction and optional telemetry behavior.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'pass',
        contextReduction: 'no',
        setupReversibility: 'strong',
      },
    },
    {
      key: 'hol-guard',
      name: 'HOL Guard',
      kind: 'plugin',
      description:
        'A scanner and runtime-guard project for agent plugins, MCP servers, skills, and tool calls.',
      aliases: ['Plugin Scanner'],
      identity: { scheme: 'github_repository', value: 'hashgraph-online/hol-guard' },
      version: { label: 'observed-2026-09-25' },
      lifecycle: 'active',
      domains: ['skills-plugins', 'observability-evaluation'],
      capability: {
        key: 'agent-extension-security-scanning',
        name: 'Scan agent extensions for security signals',
        description:
          'Produce structured findings for plugin, skill, MCP, manifest, and runtime policy surfaces.',
        deliveryMode: 'local-cli-and-runtime-integration',
        assertionState: 'publisher_declared',
        effects: ['read_data', 'execute_process'],
      },
      licenseBusiness: 'Canonical repository identifies Apache-2.0.',
      sources: [
        source(
          'repo',
          'https://github.com/hashgraph-online/hol-guard',
          'HOL Guard repository',
          'Hashgraph Online',
          'canonical_repository',
          'Scanner/runtime scope and license',
          'Repository is active and identifies Apache-2.0.',
        ),
        source(
          'docs',
          'https://github.com/hashgraph-online/hol-guard/blob/main/README.md',
          'HOL Guard documentation',
          'Hashgraph Online',
          'official_docs',
          'Publisher-described scanning and runtime behavior',
          'Documentation describes scanning and structured reports plus host-dependent runtime guard behavior.',
        ),
      ],
      claims: [
        claim(
          'scan',
          'docs',
          'HOL Guard publisher',
          'scans',
          ['plugins', 'skills', 'MCP configuration'],
          'Publisher-documented scanner scope.',
          ['Rule coverage and false positives or negatives remain tool-version specific.'],
        ),
        claim(
          'runtime',
          'docs',
          'HOL Guard publisher',
          'offers',
          'host-dependent runtime guard',
          'Publisher-documented integration surface.',
          ['No HOL Guard runtime protection is active for Maestro and no coverage is claimed.'],
        ),
      ],
      scoreDimensions: dimensions(64, 56, 94, 58, 82, {
        publisherHeavy: true,
        highPrivilege: true,
      }),
      verificationFactors: factors({
        evidence_gap: 3,
        privilege_blast_radius: 3,
        benchmarkability: 3,
        novelty_provenance: 2,
      }),
      verificationContext: verificationContext(),
      verificationState: 'candidate',
      verificationModes: ['source_review', 'static_scan', 'functional_black_box'],
      nextVerification:
        'Measure exact host coverage and calibrate findings against a labeled fixture corpus; never map its aggregate to trust.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'unknown',
        noAutomaticWorkspaceWrites: 'unknown',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
    {
      key: 'python',
      name: 'Python',
      kind: 'language',
      description:
        'A mature general-purpose programming language and runtime governed by the Python community and PSF.',
      aliases: ['CPython'],
      identity: { scheme: 'website', value: 'python.org' },
      version: { label: '3.14.7', releasedAt: '2026-08-05T00:00:00.000Z' },
      lifecycle: 'active',
      domains: ['languages-runtimes'],
      capability: {
        key: 'general-purpose-programming-runtime',
        name: 'Run general-purpose Python software',
        description: 'Provide a maintained programming language and reference runtime.',
        deliveryMode: 'language-and-runtime',
        assertionState: 'verified_for_scope',
        effects: ['execute_process'],
      },
      licenseBusiness:
        'Python 3.14 documentation publishes the PSF License Version 2 and bundled component notices.',
      sources: [
        source(
          'releases',
          'https://www.python.org/downloads/',
          'Python downloads and active releases',
          'Python Software Foundation',
          'release',
          'Release and support state',
          'Python 3.14 is in bugfix support; the page lists 3.14.7 released 2026-08-05.',
        ),
        source(
          'license',
          'https://docs.python.org/3/license.html',
          'Python history and license',
          'Python Software Foundation',
          'official_docs',
          'Python distribution license',
          'Python 3.14 documentation contains the Python Software Foundation License Version 2.',
        ),
        source(
          'security',
          'https://devguide.python.org/developer-workflow/psrt/',
          'Python security response process',
          'Python project',
          'official_docs',
          'Project security reporting and response process',
          'Python developer guidance documents a security response process.',
        ),
      ],
      claims: [
        claim(
          'release',
          'releases',
          'Python project',
          'current_bugfix_release',
          '3.14.7',
          'python.org active release records observed 2026-09-25.',
          [
            'A current language release does not validate a project package set or binary distribution.',
          ],
        ),
        claim(
          'license',
          'license',
          'Python Software Foundation',
          'distributed_under',
          'PSF License Version 2 plus component notices',
          'Python 3.14 documentation.',
          ['Exact obligations depend on the distributed version and bundled components.'],
        ),
      ],
      scoreDimensions: dimensions(98, 94, 96, 90, 98),
      verificationFactors: factors({
        evidence_gap: 0,
        privilege_blast_radius: 0,
        project_criticality: 1,
        novelty_provenance: 0,
        claim_magnitude_conflict: 0,
        benchmarkability: 0,
        decision_urgency: 0,
        irreversibility_switching_cost: 1,
      }),
      verificationContext: verificationContext({ noActiveDecisionInReviewHorizon: true }),
      verificationState: 'not_needed_for_scope',
      verificationModes: ['identity_metadata', 'documentation_contract', 'provenance_license'],
      nextVerification:
        'Do not audit Python generically; verify the exact version, distribution, packages, platform, and license scope for a project.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'pass',
        contextReduction: 'no',
        setupReversibility: 'strong',
      },
    },
    {
      key: 'terraform',
      name: 'Terraform',
      kind: 'runtime',
      description:
        'An established infrastructure-as-code engine with a distinct provider ecosystem and hosted products.',
      aliases: ['Terraform Core'],
      identity: { scheme: 'github_repository', value: 'hashicorp/terraform' },
      version: { label: '1.16.2' },
      lifecycle: 'active',
      domains: ['infrastructure-as-code'],
      capability: {
        key: 'infrastructure-as-code',
        name: 'Plan and apply infrastructure state',
        description:
          'Describe infrastructure declaratively and calculate or apply state transitions through providers.',
        deliveryMode: 'cli-and-provider-ecosystem',
        assertionState: 'verified_for_scope',
        effects: ['read_data', 'write_data', 'network', 'credential_use', 'external_mutation'],
      },
      licenseBusiness:
        'Terraform 1.6.0 and later is under Business Source License 1.1 with stated additional-use and change terms.',
      sources: [
        source(
          'docs',
          'https://developer.hashicorp.com/terraform/docs',
          'Terraform documentation',
          'HashiCorp / IBM',
          'official_docs',
          'Core infrastructure-as-code behavior',
          'Official docs describe Terraform configuration, planning, state, and provider integrations.',
        ),
        source(
          'releases',
          'https://github.com/hashicorp/terraform/releases',
          'Terraform releases',
          'HashiCorp / IBM',
          'release',
          'Version and release state',
          'Canonical releases page lists 1.16.2 as the current stable release near the observation date.',
        ),
        source(
          'license',
          'https://github.com/hashicorp/terraform/blob/main/LICENSE',
          'Terraform license',
          'IBM',
          'commercial_terms',
          'Current core source license',
          'License applies BSL 1.1 to Terraform 1.6.0 or later with a four-year change date to MPL 2.0.',
        ),
      ],
      claims: [
        claim(
          'iac',
          'docs',
          'Terraform publisher',
          'provides_capability',
          'infrastructure-as-code planning and application',
          'Terraform core documentation.',
          ['Providers, state backends, and hosted services have separate identities and risks.'],
        ),
        claim(
          'license',
          'license',
          'IBM',
          'distributed_under',
          'Business Source License 1.1 for version 1.6.0 or later',
          'Current Terraform core license parameters.',
          ['License compatibility must be assessed for the exact version and use.'],
        ),
      ],
      scoreDimensions: dimensions(94, 90, 94, 82, 96, { highPrivilege: true }),
      verificationFactors: factors({
        evidence_gap: 0,
        novelty_provenance: 0,
        claim_magnitude_conflict: 0,
        privilege_blast_radius: 2,
        project_criticality: 1,
        benchmarkability: 0,
        decision_urgency: 0,
        irreversibility_switching_cost: 2,
      }),
      verificationContext: verificationContext({ noActiveDecisionInReviewHorizon: true }),
      verificationState: 'not_needed_for_scope',
      verificationModes: ['identity_metadata', 'documentation_contract', 'provenance_license'],
      nextVerification:
        'Do not audit Terraform generically; inspect the exact core/provider versions, license, state backend, credentials, plan, and apply permissions.',
      compatibility: {
        noRemoteSourceTransfer: 'pass',
        macos: 'pass',
        noAutomaticWorkspaceWrites: 'fail',
        contextReduction: 'no',
        setupReversibility: 'mixed',
      },
    },
  ],
};
