import type { CorpusRecord } from './phase06-corpus.js';

// This broadens the deterministic offline fixture with source-backed identity and
// publisher-scope metadata. These are proposed records, not efficacy or project-fit judgments.
export const discoveryCorpusV1: CorpusRecord[] = [
  {
    key: 'openai-provider',
    name: 'OpenAI',
    kind: 'service',
    capabilityKey: 'ai-model-provider',
    capabilityName: 'AI model provider',
    summary:
      'A provider of model families and APIs for language, reasoning, image, audio, and agent applications.',
    searchText:
      'ai artificial intelligence provider models model family inference api multimodal agents',
    aliases: ['OpenAI models', 'OpenAI API'],
    sourceUrl: 'https://developers.openai.com/api/docs/models',
    sourceTitle: 'OpenAI models documentation',
    sourceOwner: 'OpenAI',
    domainKey: 'ai-providers',
  },
  {
    key: 'anthropic-provider',
    name: 'Anthropic',
    kind: 'service',
    capabilityKey: 'ai-model-provider',
    capabilityName: 'AI model provider',
    summary: 'A provider of the Claude model family and APIs for language and agent applications.',
    searchText:
      'ai artificial intelligence provider claude models model family inference api agents',
    aliases: ['Anthropic Claude', 'Claude provider'],
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
    sourceTitle: 'Anthropic model overview',
    sourceOwner: 'Anthropic',
    domainKey: 'ai-providers',
  },
  {
    key: 'google-gemini-provider',
    name: 'Google Gemini',
    kind: 'service',
    capabilityKey: 'ai-model-provider',
    capabilityName: 'AI model provider',
    summary: 'Google model families and APIs for multimodal generative AI applications.',
    searchText:
      'ai artificial intelligence provider gemini models model family multimodal inference api',
    aliases: ['Gemini API', 'Google AI models'],
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    sourceTitle: 'Gemini models documentation',
    sourceOwner: 'Google',
    domainKey: 'ai-providers',
  },
  {
    key: 'gpt-model-family',
    name: 'GPT model family',
    kind: 'model',
    capabilityKey: 'general-purpose-ai-model-family',
    capabilityName: 'General-purpose AI model family',
    summary:
      'A family of OpenAI language and reasoning models with dated variants documented by the provider.',
    searchText:
      'ai artificial intelligence model models model family gpt language reasoning multimodal release',
    aliases: ['GPT models', 'Generative Pre-trained Transformer'],
    sourceUrl: 'https://developers.openai.com/api/docs/models',
    sourceTitle: 'OpenAI models documentation',
    sourceOwner: 'OpenAI',
    domainKey: 'ai-model-families',
  },
  {
    key: 'claude-model-family',
    name: 'Claude model family',
    kind: 'model',
    capabilityKey: 'general-purpose-ai-model-family',
    capabilityName: 'General-purpose AI model family',
    summary:
      'A family of Anthropic language and reasoning models with dated variants documented by the provider.',
    searchText:
      'ai artificial intelligence model models model family claude language reasoning multimodal release',
    aliases: ['Claude models'],
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
    sourceTitle: 'Anthropic model overview',
    sourceOwner: 'Anthropic',
    domainKey: 'ai-model-families',
  },
  {
    key: 'gemini-model-family',
    name: 'Gemini model family',
    kind: 'model',
    capabilityKey: 'general-purpose-ai-model-family',
    capabilityName: 'General-purpose AI model family',
    summary:
      'A family of Google multimodal generative models with variants documented by the provider.',
    searchText:
      'ai artificial intelligence model models model family gemini language reasoning multimodal release',
    aliases: ['Gemini models'],
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    sourceTitle: 'Gemini models documentation',
    sourceOwner: 'Google',
    domainKey: 'ai-model-families',
  },
  {
    key: 'llama-model-family',
    name: 'Llama model family',
    kind: 'model',
    capabilityKey: 'open-weight-ai-model-family',
    capabilityName: 'Open-weight AI model family',
    summary:
      'A family of Meta-published open-weight language models with versioned model cards and licenses.',
    searchText:
      'ai artificial intelligence model models model family llama open weight language inference release',
    aliases: ['Meta Llama', 'Llama models'],
    sourceUrl: 'https://www.llama.com/docs/model-cards-and-prompt-formats/',
    sourceTitle: 'Llama model cards and prompt formats',
    sourceOwner: 'Meta',
    domainKey: 'ai-model-families',
  },
  {
    key: 'kubernetes',
    name: 'Kubernetes',
    kind: 'oss_project',
    capabilityKey: 'container-orchestration',
    capabilityName: 'Container orchestration',
    summary:
      'An open-source system for automating deployment, scaling, and management of containerized applications.',
    searchText:
      'devops containers orchestration cluster deployment operations cloud native kubernetes',
    aliases: ['K8s', 'Kubernetes orchestration'],
    sourceUrl: 'https://kubernetes.io/docs/concepts/overview/',
    sourceTitle: 'Kubernetes overview',
    sourceOwner: 'Kubernetes project',
    domainKey: 'containers-orchestration',
  },
  {
    key: 'docker',
    name: 'Docker',
    kind: 'runtime',
    capabilityKey: 'container-platform',
    capabilityName: 'Container platform',
    summary: 'A platform and toolchain for building, distributing, and running container images.',
    searchText: 'devops container containers image runtime build distribute run docker',
    aliases: ['Docker Engine', 'Docker containers'],
    sourceUrl: 'https://docs.docker.com/get-started/docker-overview/',
    sourceTitle: 'Docker overview',
    sourceOwner: 'Docker',
    domainKey: 'containers-orchestration',
  },
  {
    key: 'helm',
    name: 'Helm',
    kind: 'oss_project',
    capabilityKey: 'kubernetes-package-management',
    capabilityName: 'Kubernetes package management',
    summary:
      'A package manager for defining, installing, and upgrading Kubernetes applications with charts.',
    searchText: 'devops kubernetes package manager charts deployment release helm',
    aliases: ['Helm charts', 'Kubernetes Helm'],
    sourceUrl: 'https://helm.sh/docs/topics/architecture/',
    sourceTitle: 'Helm architecture',
    sourceOwner: 'Helm project',
    domainKey: 'containers-orchestration',
  },
  {
    key: 'prometheus',
    name: 'Prometheus',
    kind: 'oss_project',
    capabilityKey: 'metrics-monitoring',
    capabilityName: 'Metrics monitoring',
    summary: 'An open-source monitoring and alerting system centered on time-series metrics.',
    searchText: 'devops observability monitoring metrics alerting reliability prometheus',
    aliases: ['Prometheus monitoring'],
    sourceUrl: 'https://prometheus.io/docs/introduction/overview/',
    sourceTitle: 'Prometheus overview',
    sourceOwner: 'Prometheus project',
    domainKey: 'observability-reliability',
  },
  {
    key: 'opentelemetry',
    name: 'OpenTelemetry',
    kind: 'standard',
    capabilityKey: 'telemetry-instrumentation',
    capabilityName: 'Telemetry instrumentation',
    summary:
      'A vendor-neutral observability framework and specification for traces, metrics, and logs.',
    searchText:
      'devops observability telemetry traces metrics logs standard specification opentelemetry',
    aliases: ['OTel', 'OpenTelemetry specification'],
    sourceUrl: 'https://opentelemetry.io/docs/what-is-opentelemetry/',
    sourceTitle: 'What is OpenTelemetry?',
    sourceOwner: 'OpenTelemetry project',
    domainKey: 'observability-reliability',
  },
  {
    key: 'argo-cd',
    name: 'Argo CD',
    kind: 'oss_project',
    capabilityKey: 'gitops-continuous-delivery',
    capabilityName: 'GitOps continuous delivery',
    summary: 'A declarative GitOps continuous-delivery controller for Kubernetes.',
    searchText: 'devops gitops continuous delivery cd kubernetes deployment controller argo',
    aliases: ['ArgoCD'],
    sourceUrl: 'https://argo-cd.readthedocs.io/en/stable/',
    sourceTitle: 'Argo CD documentation',
    sourceOwner: 'Argo project',
    domainKey: 'delivery-automation',
  },
  {
    key: 'gitops-practice',
    name: 'GitOps',
    kind: 'practice',
    capabilityKey: 'declarative-operations-practice',
    capabilityName: 'Declarative operations practice',
    summary:
      'An operational practice using declarative desired state, version control, and automated reconciliation.',
    searchText:
      'devops practice gitops declarative version control reconciliation delivery operations',
    aliases: ['Git operations'],
    sourceUrl: 'https://opengitops.dev/',
    sourceTitle: 'OpenGitOps principles',
    sourceOwner: 'OpenGitOps',
    domainKey: 'delivery-automation',
  },
  {
    key: 'sre-practice',
    name: 'Site reliability engineering',
    kind: 'practice',
    capabilityKey: 'site-reliability-engineering',
    capabilityName: 'Site reliability engineering',
    summary:
      'An engineering discipline for operating reliable services through objectives, automation, and measured risk.',
    searchText:
      'devops sre site reliability engineering practice service level objective error budget operations',
    aliases: ['SRE'],
    sourceUrl: 'https://sre.google/sre-book/introduction/',
    sourceTitle: 'Site Reliability Engineering introduction',
    sourceOwner: 'Google',
    domainKey: 'observability-reliability',
  },
  {
    key: 'pytorch',
    name: 'PyTorch',
    kind: 'framework',
    capabilityKey: 'machine-learning-framework',
    capabilityName: 'Machine-learning framework',
    summary:
      'An open-source tensor and deep-learning framework for model development and deployment.',
    searchText: 'ml machine learning deep learning neural network model training framework pytorch',
    aliases: ['Torch', 'PyTorch ML'],
    sourceUrl: 'https://pytorch.org/docs/stable/index.html',
    sourceTitle: 'PyTorch documentation',
    sourceOwner: 'PyTorch Foundation',
    domainKey: 'machine-learning',
  },
  {
    key: 'tensorflow',
    name: 'TensorFlow',
    kind: 'framework',
    capabilityKey: 'machine-learning-framework',
    capabilityName: 'Machine-learning framework',
    summary:
      'An end-to-end open-source platform for machine-learning model development and deployment.',
    searchText:
      'ml machine learning deep learning neural network model training framework tensorflow',
    aliases: ['TensorFlow ML'],
    sourceUrl: 'https://www.tensorflow.org/guide',
    sourceTitle: 'TensorFlow guide',
    sourceOwner: 'TensorFlow',
    domainKey: 'machine-learning',
  },
  {
    key: 'scikit-learn',
    name: 'scikit-learn',
    kind: 'library',
    capabilityKey: 'classical-machine-learning',
    capabilityName: 'Classical machine learning',
    summary:
      'A Python library for supervised and unsupervised learning, preprocessing, model selection, and evaluation.',
    searchText:
      'ml machine learning supervised unsupervised model evaluation preprocessing python library scikit learn',
    aliases: ['sklearn', 'scikit learn'],
    sourceUrl: 'https://scikit-learn.org/stable/user_guide.html',
    sourceTitle: 'scikit-learn user guide',
    sourceOwner: 'scikit-learn project',
    domainKey: 'machine-learning',
  },
  {
    key: 'mlflow',
    name: 'MLflow',
    kind: 'platform',
    capabilityKey: 'machine-learning-lifecycle',
    capabilityName: 'Machine-learning lifecycle',
    summary:
      'An open-source platform for tracking experiments, packaging models, registry workflows, and deployment metadata.',
    searchText:
      'ml machine learning operations mlops experiment tracking model registry deployment lifecycle mlflow',
    aliases: ['MLflow tracking'],
    sourceUrl: 'https://mlflow.org/docs/latest/ml/',
    sourceTitle: 'MLflow machine learning documentation',
    sourceOwner: 'MLflow project',
    domainKey: 'machine-learning',
  },
  {
    key: 'supervised-learning',
    name: 'Supervised learning',
    kind: 'practice',
    capabilityKey: 'supervised-learning-method',
    capabilityName: 'Supervised learning method',
    summary:
      'A learning method that estimates mappings from labeled examples for classification or regression.',
    searchText:
      'ml machine learning method supervised labeled data classification regression training concept',
    aliases: ['Supervised ML'],
    sourceUrl: 'https://scikit-learn.org/stable/supervised_learning.html',
    sourceTitle: 'scikit-learn supervised learning guide',
    sourceOwner: 'scikit-learn project',
    domainKey: 'machine-learning',
  },
  {
    key: 'reinforcement-learning',
    name: 'Reinforcement learning',
    kind: 'practice',
    capabilityKey: 'reinforcement-learning-method',
    capabilityName: 'Reinforcement learning method',
    summary:
      'A learning paradigm in which an agent improves behavior through actions, observations, and rewards.',
    searchText:
      'ml machine learning method reinforcement learning agent reward policy environment concept',
    aliases: ['RL', 'Reinforcement ML'],
    sourceUrl: 'https://spinningup.openai.com/en/latest/spinningup/rl_intro.html',
    sourceTitle: 'Introduction to reinforcement learning',
    sourceOwner: 'OpenAI',
    domainKey: 'machine-learning',
  },
  {
    key: 'rust-language',
    name: 'Rust',
    kind: 'language',
    capabilityKey: 'systems-programming-language',
    capabilityName: 'Systems programming language',
    summary:
      'A programming language focused on performance, type safety, and memory safety without garbage collection.',
    searchText: 'cs computer science programming language systems compiler memory safety rust',
    aliases: ['Rust language'],
    sourceUrl: 'https://doc.rust-lang.org/book/',
    sourceTitle: 'The Rust Programming Language',
    sourceOwner: 'Rust project',
    domainKey: 'programming-languages',
  },
  {
    key: 'typescript-language',
    name: 'TypeScript',
    kind: 'language',
    capabilityKey: 'typed-programming-language',
    capabilityName: 'Typed programming language',
    summary: 'A typed language that builds on JavaScript and compiles to JavaScript.',
    searchText:
      'cs computer science programming language type system compiler javascript typescript',
    aliases: ['TS language'],
    sourceUrl: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    sourceTitle: 'TypeScript handbook',
    sourceOwner: 'Microsoft',
    domainKey: 'programming-languages',
  },
  {
    key: 'algorithms-concept',
    name: 'Algorithms',
    kind: 'practice',
    capabilityKey: 'algorithm-design-analysis',
    capabilityName: 'Algorithm design and analysis',
    summary: 'Finite procedures and analysis techniques for solving computational problems.',
    searchText:
      'cs computer science algorithm algorithms complexity design analysis computation concept',
    aliases: ['Algorithm design'],
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/',
    sourceTitle: 'MIT Introduction to Algorithms',
    sourceOwner: 'MIT OpenCourseWare',
    domainKey: 'computer-science',
  },
  {
    key: 'distributed-systems-concept',
    name: 'Distributed systems',
    kind: 'practice',
    capabilityKey: 'distributed-systems',
    capabilityName: 'Distributed systems',
    summary:
      'Systems whose components coordinate across networked computers under partial failure and concurrency.',
    searchText:
      'cs computer science distributed systems network concurrency consensus fault tolerance concept',
    aliases: ['Distributed computing'],
    sourceUrl: 'https://pdos.csail.mit.edu/6.824/',
    sourceTitle: 'MIT Distributed Systems',
    sourceOwner: 'MIT CSAIL',
    domainKey: 'computer-systems',
  },
  {
    key: 'database-systems-concept',
    name: 'Database systems',
    kind: 'practice',
    capabilityKey: 'database-systems',
    capabilityName: 'Database systems',
    summary:
      'Systems and techniques for durable data models, queries, transactions, indexing, and recovery.',
    searchText:
      'cs computer science database systems sql transaction index recovery storage concept',
    aliases: ['Databases', 'DBMS'],
    sourceUrl: 'https://15445.courses.cs.cmu.edu/',
    sourceTitle: 'CMU Database Systems',
    sourceOwner: 'Carnegie Mellon University',
    domainKey: 'computer-systems',
  },
];
